export const uoMaskParse = (val: bigint): UoMask => ({
    menuCall                    : Boolean(val & 2n** 0n),
    titleSearch                 : Boolean(val & 2n** 1n),
    chapterSearch               : Boolean(val & 2n** 2n),
    timeSearch                  : Boolean(val & 2n** 3n),
    skipToNextPoint             : Boolean(val & 2n** 4n),
    skiptoPrevPoint             : Boolean(val & 2n** 5n),
    playFirstplay               : Boolean(val & 2n** 6n),
    stop                        : Boolean(val & 2n** 7n),
    pauseOn                     : Boolean(val & 2n** 8n),
    pauseOff                    : Boolean(val & 2n** 9n),
    stillOff                    : Boolean(val & 2n**10n),
    forward                     : Boolean(val & 2n**11n),
    backward                    : Boolean(val & 2n**12n),
    resume                      : Boolean(val & 2n**13n),
    moveUp                      : Boolean(val & 2n**14n),
    moveDown                    : Boolean(val & 2n**15n),
    moveLeft                    : Boolean(val & 2n**16n),
    moveRight                   : Boolean(val & 2n**17n),
    select                      : Boolean(val & 2n**18n),
    activate                    : Boolean(val & 2n**19n),
    selectAndActivate           : Boolean(val & 2n**20n),
    primaryAudioChange          : Boolean(val & 2n**21n),
    // SKIP                     : Boolean(val & 2n**22n),
    angleChange                 : Boolean(val & 2n**23n),
    popupOn                     : Boolean(val & 2n**24n),
    popupOff                    : Boolean(val & 2n**25n),
    pgEnableDisable             : Boolean(val & 2n**26n),
    pgChange                    : Boolean(val & 2n**27n),
    secondaryVideoEnableDisable : Boolean(val & 2n**28n),
    secondaryVideoChange        : Boolean(val & 2n**29n),
    secondaryAudioEnableDisable : Boolean(val & 2n**30n),
    secondaryAudioChange        : Boolean(val & 2n**31n),
    // SKIP                     : Boolean(val & 2n**32n),
    pipPgChange                 : Boolean(val & 2n**33n),
});